### ISSUE TITLE
Add support for CTM (color transformation matrix)

### ISSUE THREAD

**Issue by sfiedler0** [hyprwm/aquamarine#89] opened 2024-09-30 18:29 UTC
I am currently working on Asahi Linux with Hyprland. Everything works perfectly, except for night light. After some research I found AsahiLinux/docs#67.  
The mentioned gammastep issue had a comment pointing to an issue in wlroots. As Hyprland is independent now (and uses aquamarine which does the gamma LUT stuff), I thought it'd be a great idea to implement the CTM here too.

**Comment by vaxerski** [comment] 2024-09-30 20:24
hm, the problem is that wl-sunset et al that control this on hyprland via the wlr gamma protocol can only provide a ramp, not a matrix. How would we control the amount of red-shifting?

**Comment by sfiedler0** [comment] 2024-10-01 13:42
I don't know exactly how, but KDE has CTM support merged: https://invent.kde.org/plasma/kwin/-/merge_requests/3296

**Comment by vaxerski** [comment] 2024-10-01 13:43
they dont have to support stuff like wl-sunset though (and they dont)

while we do

**Comment by sfiedler0** [comment] 2024-10-01 13:47
I know, but they have some way to adjust the night light in the settings.

**Comment by vaxerski** [comment] 2024-10-01 15:18
no, they didnt

**Comment by sfiedler0** [comment] 2024-10-07 15:36
So CTM control is ready for a new wlr protocol?

**Comment by vaxerski** [comment] 2024-10-07 15:38
wlr makes no sense (we arent wlr anymore)

I'd either:
- find out a method to convert gamma ramps to a ctm
- ditch the external apps altogether, just make the ctm a configurable thing in the config
- make a new hyprland protocol for ctm - could actually be nice with a hyprland-provided utility for night light

**Comment by vaxerski** [comment] 2024-10-07 15:39
looking at drm support it seems that all drivers support CTMs. Well, all that matter. AMD, Nvidia, Intel.

**Comment by vaxerski** [comment] 2024-10-07 15:41
I'll try to draft a protocol later today if I don't forget at hyprland-protocols. Ping me tomorrow if I don't

**Comment by vaxerski** [comment] 2024-10-07 23:47
closing this as aquamarine is done. Hyprland see https://github.com/hyprwm/Hyprland/pull/8023, client see https://github.com/hyprwm/hyprsunset.

If you compile from 8023 you should be able to use hyprsunset no problem, tested on my machine, but lmk if it works on apple.

cheers

**Closed by vaxerski** 2024-10-07 23:47 UTC

**Comment by littleblack111** [comment] 2024-10-10 13:24
> they dont have to support stuff like wl-sunset though (and they dont)
> 
> while we do

updated and hyprsunset works, while wlsunset doesnt:
```
registry: adding output 51
gamma control of output DP-2 (51) failed
calculated sun trajectory: polar night
setting temperature to 4000 K
gamma control of output DP-2 (51) failed
```

is it going to be supported soon or is that unexpected

**Comment by vaxerski** [comment] 2024-10-10 20:24
wlsunset only supports gamma ramps

**Comment by tikhonp** [comment] 2024-11-10 16:46
Any way to adjust color temperature in SwayWM? Neither `redshift` nor `wlsunset` dont work :(
